export const Status = {
    "EMAIL_REQUIRED": { name: 'Please enter Email ID' },
    "EMAIL_INVALID": { name: 'Invalid Email' },
    "PASSWORD_REQUIRED": { name: 'Please set a password' },
    "PASSWORD_CURRENT": { name: 'Please enter current password' },
    "PASSWORD_LEAST": { name: 'Password must be at least 7 characters' },
    "PASSWORD_EXCEED": { name: 'Password must not exceed 40 characters' },
    "PASSWORD_WEEK": { name: 'Password is too weak' },
    "VERIFICATION_REQUIRED": { name: 'Please enter Verification Code' },
    "VERIFICATION_OTP_LEAST": { name: 'Inavlid OTP entered' },
    "SESSION_EXPIRED": { name: 'Your session has expired.Please login again' },
    "EMAIL_NOT_VERIFY": { name: 'Email ID not verified' },
    "SSO_NOT_ALLOW_FORGOT_PASSWORD": { name: 'SSO user not allowed. Perform forgot-password' },
    "FULL_NAME_REQUIRED": { name: 'Please enter your Full Name' },
    "TITLE_REQUIRED": { name: 'Please enter your Title' },
    "BIRTH_DATE_REQUIRED": { name: 'Please enter your Birth Date' },
    "MOBILE_NUMBER_REQUIRED": { name: 'Please enter your Mobile Number' },
    "MOBILE_NUMBER_LEAST_NUMBER": { name: 'Mobile number must be at least 10 numbers' },
    "PASSWORD_CHARACTERS": { name: 'Password must be at least 8 characters. Password should include Lower Case,Upper Case, Digits, Special Characters(@,$,#,%,&,*)'},
    // "PASSWORD_CHARACTERS": { name: 'Mininum of different classes of characters in password is 3. Classes of characters: Lower Case,Upper Case, Digits, Special Characters(@,$,#,%,&,*). Password must be at least 7 characters' },
    "CONFIRM_PWD_REQUIRED": { name: 'Please Confirm Password' },
    "CONFIRM_PWD_NOT_MATCH": { name: 'Passwords do not match' },
    "TERMS_CONDITION_REQUIRED": { name: 'Please agree to all the terms and conditions before signing up' },
    "PURCHASE_BUDDY_BUCKS": { name: 'Purchase Buddy Bucks' },
    "DESCRIPTION_REQUIRED": { name: 'Please enter your Description' },
    "SELECT_IMAGE_REQUIRED": { name: 'Please Select your Image' },
    "SELECT_YOUR_FILE": { name: 'Please select your file' },
    "PURCHASE_BADGES": { name: 'Purchase Badges' },
    "FREE_BADGES": { name: 'My Badges' },
    "OTHER_BADGES": { name: 'Other Badges' },
    "PURCHASE_BELTS": { name: 'will not exist as we cannot purchase Belts' },
    "FREE_BELTS": { name: 'will not exist as we cannot purchase Belts' },
    "OTHER_BELTS": { name: 'will not exist as we cannot purchase Belts' },
    "PERSONAL_DATA": { name: 'Personal Data' },
    "GENDER_REQUIRED": { name: 'Please enter Gender' },
    "BRAWLS_HISTORY": { name: 'Brawls History' },
    "REFER_FRIEND": { name: 'Refer a friend' },
    "TRANSACTION_HISTORY": { name: 'Transaction History' },
    "RESET_PWD": { name: 'Reset Password' },
    "NEW_PWD_REQUIRED": { name: 'Please enter a new password' },
    "PWD_REQUIRED": { name: 'Please enter password' },
    "PROFILE_UPDATE": { name: 'Your profile picture was succesfully updated' },
    "PROFILE_UPDATE_SUCCESS": { name: 'Profile Updated Successfully' },
    "VALID_FILE": { name: 'Please upload a valid file' },
    "LOGOUT": { name: 'You are Logged Out' },
    "REFERRAL_LINK": { name: 'Referral link copied successfully' },
    "NO_DATA_FOUND": { name: 'No Data Found' },
    "MAXIMUM_BRAWLS_SELECT": { name: 'Maximum 5 bets allowed' },
    "MINIMUM_WAGER_ENTER": { name: 'Minimum wager to enter brawl is 10,000 Buddy Bucks' },
    "JOIN_BRAWL_SUCCESS": { name: 'Joined Brawl successfully' },
    "SEE_MORE": { name: 'See More' },
    "SELECT_ONE_GAME": { name: 'Select one game' },
    "SELECT_DATE_TIME": { name: 'Select date & time' },
    "SELECT_SIZE_CONTEST": { name: 'Select Contest Size' },
    "TITLE_NAME_REQ": { name: 'Please enter Brawl Title' },
    "ENTRY_FEES_REQ": { name: 'Please enter Entry Fees' },
    "BADGE_REQ": { name: 'Please select Badge' },
    "FEATURES_REQ": { name: 'Please select whether the brawl is featured or not' },
    "ADD_BUDDY": { name: 'Buddy added successfully' },
    "SUPPORT_MAIL": { name: 'Thank you for contacting BuddyBrawl. We will reply you back on email.' },
    "REMOVE_BUDDY": { name: 'Buddy removed successfully' },
    "CREATE_BRAWL": { name: 'Brawl created successfully' },
    "INVITE_BUDDY": { name: 'Buddy invited successfully' },
    "PURCHASE_SUCCESS": { name: ' Purchase Successfully' },
    "CREDIT_BADGES_SUCCESS": { name: 'Credit badges Successfully' },
    "BADGES_NOT_SELECT": { name: 'Badges Not Selected' },
    "AUTHORIZATION" : { name: 'authorization=' },
    "MAXIMUM_WAGER_ENTER": { name: 'Maximum $10000 Wager Required' },
    "MAXIMUM_200_ENTER": { name: 'Minimum $200 Wager Required' },
    "SELECT_MINIMUM_FIVE_SLIP": { name: 'Please select 5 slips to enter a Brawl' },
    "FILL_WAGER": { name: 'Please fill wager amount' },
}
